apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: omniforge-production

replicas:
  - name: omniforge-backend
    count: 5

images:
  - name: ghcr.io/chaitanyajoshi1769/omniforge-ai
    newTag: v0.0.1

patchesStrategicMerge:
  - deployment-patch.yaml

resources:
  - network-policy.yaml
  - pod-disruption-budget.yaml

commonLabels:
  environment: production

commonAnnotations:
  environment: production
